// Header file automatically generated by CMake that aggregates all the headers.
// Do not edit!

#ifndef _ALLGRABBERS_H_
#define _ALLGRABBERS_H_

#pragma once

#include "FrameSequenceWriter.h"
#include "Grabber.h"
#include "GrabberCMU1394.h"
#include "GrabberControls.h"
#include "GrabberDefinitions.h"
#include "GrabberFileImage.h"
#include "GrabberMode.h"
#include "GrabberOpenCVCamera.h"
#include "GrabberOpenCVCapture.h"
#include "GrabberOpenCVFileVideo.h"
#include "GrabberProperties.h"
#include "GrabberPS3Eye.h"
#include "GrabberSVS.h"
#include "GrabberSVSFileImage.h"
#include "GrabberSVSVideo.h"
#include "GrabberYARPPort.h"
#include "ImageStream.h"

#endif // _ALLGRABBERS_H_
