//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PHRI.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PHRI_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       131
#define IDB_Author                      133
#define IDB_CONFIG                      136
#define IDB_EXIT                        140
#define IDB_SAVE                        141
#define IDB_LOAD                        142
#define IDB_HELP                        143
#define IDB_CONFIGURATION               144
#define IDB_CONF                        145
#define IDC_GCONF                       1001
#define IDC_EJ0                         1003
#define IDC_EJ1                         1004
#define IDC_EJ2                         1006
#define IDC_EJ3                         1007
#define IDC_EJ4                         1011
#define IDC_EJ5                         1012
#define IDC_EJ6                         1013
#define IDC_EJ7                         1014
#define IDC_ET                          1015
#define IDC_BCC                         1016
#define IDC_EX                          1017
#define IDC_EX2                         1018
#define IDC_CPA                         1019
#define IDC_EPA                         1020
#define IDC_TJ0                         1021
#define IDC_EY2                         1021
#define IDC_TJ1                         1022
#define IDC_TJ2                         1023
#define IDC_EZ2                         1023
#define IDC_TJ3                         1024
#define IDC_EYAW                        1024
#define IDC_TJ4                         1025
#define IDC_EPIT                        1025
#define IDC_TJ5                         1026
#define IDC_EROL                        1026
#define IDC_TJ6                         1027
#define IDC_EVM                         1027
#define IDC_TJ7                         1028
#define IDC_EWM                         1028
#define IDC_BCGH                        1029
#define IDC_BCGR                        1030
#define IDC_BJMM                        1031
#define IDC_EB                          1033
#define IDC_EY                          1034
#define IDC_EZ                          1035
#define IDC_EC                          1036
#define IDC_BAMM                        1037
#define IDC_BHMM                        1038
#define IDC_EA                          1039
#define IDC_SX                          1040
#define IDC_SY                          1041
#define IDC_SZ                          1042
#define IDC_SA                          1043
#define IDC_SB                          1044
#define IDC_SC                          1045
#define IDC_BMM                         1046
#define IDC_SS                          1049
#define IDC_SYAW                        1052
#define IDC_KJ1                         1053
#define IDC_SPIT                        1053
#define IDC_KJ2                         1054
#define IDC_SROL                        1054
#define IDC_BMV                         1055
#define IDC_BTE                         1056
#define IDC_BTC                         1057
#define IDC_SVM                         1058
#define IDC_SWM                         1059
#define IDC_SXTAR                       1060
#define IDC_SYTAR                       1061
#define IDC_SZTAR                       1062
#define IDC_SDTAR                       1063
#define IDC_SL1D                        1064
#define IDC_SPHI1                       1064
#define IDC_SXTARE                      1064
#define IDC_EVX                         1065
#define IDC_SL2D                        1066
#define IDC_SPHI2                       1066
#define IDC_SYTARE                      1066
#define IDC_SL1                         1067
#define IDC_SL3                         1067
#define IDC_SZTARE                      1067
#define IDC_SL2                         1068
#define IDC_VDS                         1069
#define IDC_VDS0                        1069
#define IDC_VDS1                        1070
#define IDC_CVX                         1071
#define IDC_EVA                         1072
#define IDC_CVA                         1073
#define IDC_EVY                         1074
#define IDC_CVY                         1075
#define IDC_EVB                         1076
#define IDC_CVB                         1077
#define IDC_EVZ                         1078
#define IDC_CVZ                         1079
#define IDC_EVC                         1080
#define IDC_CVC                         1081
#define IDC_SJ0                         1082
#define IDC_SJ1                         1083
#define IDC_SJ2                         1084
#define IDC_SJ3                         1085
#define IDC_SJ4                         1086
#define IDC_SJ5                         1087
#define IDC_SJ6                         1088
#define IDC_SJ7                         1089
#define IDC_BJMG                        1090
#define IDC_SOX                         1091
#define IDC_SOY                         1092
#define IDC_SOZ                         1093
#define IDC_SNO                         1094
#define IDC_SOA                         1095
#define IDC_LVES0                       1095
#define IDC_ST                          1096
#define IDC_CTASK                       1097
#define IDC_LVES1                       1098
#define IDC_SDT                         1099
#define IDC_SFX                         1104
#define IDC_SFY                         1105
#define IDC_SFZ                         1106
#define IDC_STX                         1107
#define IDC_STY                         1108
#define IDC_STZ                         1109
#define IDC_CHECK1                      1111
#define IDC_CHECK2                      1112
#define IDC_CHECK3                      1113
#define IDC_CHECK4                      1114
#define IDC_CHECK5                      1115
#define IDC_CHECK6                      1116
#define IDC_CHECK7                      1117
#define IDC_CHECK8                      1118
#define IDC_SSTAR                       1120
#define IDC_OBS1                        1128
#define IDC_OBS2                        1129
#define IDC_OBS3                        1130
#define IDC_OBS4                        1131
#define IDC_OBS5                        1132
#define ID_CONFIGURATION_EXIT           32773
#define ID_CONFIGURATION_LOAD           32774
#define ID_CONFIGURATION_SAVE           32775
#define ID_ABOUT_PHRI                   32776
#define ID_KINEMATICS_JOINTLIMITAVOIDANCE 32777
#define ID_KINEMATICS_SINGULARITYAVOIDANCE 32778
#define ID_KINEMATICS_OBSTACLEAVOIDANCE 32783
#define ID_CONFIGURATION_VISION         32786
#define ID_CONFIGURATION_SPEECH         32787
#define ID_CONFIGURATION_SAVE32788      32788
#define ID_CONFIGURATION_SEP            32789
#define ID_MODULES_VISION               32790
#define ID_MODULES_SPEECH               32791
#define ID_MODULES_HAND                 32792
#define ID_MODULES_NECK                 32793
#define ID_MODULES_VOICE                32794
#define ID_MODULES_MOBILE               32795
#define ID_MODULES_LASERRANGEFINDER     32796

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         1121
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
