// Header file automatically generated by CMake that aggregates all the headers.
// Do not edit!

#ifndef _ALLPROCESSIMAGE_H_
#define _ALLPROCESSIMAGE_H_

#pragma once

#include "ProcessImage.h"
#include "ProcessImageBaufix.h"
#include "ProcessImageColourLearning.h"
#include "ProcessImageComputerAssembly.h"
#include "ProcessImageDiffKin.h"
#include "ProcessImageDrinking.h"
#include "ProcessImageFaceTracking.h"
#include "ProcessImageHRTransport.h"
#include "ProcessImageMobileRobotTarget1.h"
#include "ProcessImagePlayPiano.h"
#include "ProcessImageTest.h"
#include "ProcessImageToyRobotFull_AVT.h"
#include "ProcessImageToyRobotFull_SVS.h"
#include "ProcessImageToyRobotLearning.h"
#include "ProcessImageToyRobot_SVS.h"

#endif // _ALLPROCESSIMAGE_H_
