//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VisionBot.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VISIONBOT_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDR_MAIN_MENU                   130
#define IDD_DIALOG_CONNECTION           131
#define IDD_DIALOG_PANTILT              132
#define IDD_DIALOG_SEGMENTATION         133
#define IDD_DIALOG_VIDEO_PARAMETERS     134
#define IDD_DIALOG_YARPPORT_CONFIGURATION 135
#define IDD_DIALOG_INFO_AROS            136
#define IDD_DIALOG_HUMAN_INFO           137
#define IDD_DIALOG_GESTURE_PARAMETERS   138
#define IDC_STATIC_FRAME_COUNTER        1000
#define IDC_EDIT_NAME                   1001
#define IDC_EDIT_ROUTER                 1002
#define IDC_EDIT_PAN                    1003
#define IDC_EDIT_PEER_NAME              1004
#define IDC_BUTTON_SET_PAN              1005
#define IDC_BUTTON_GET_PAN              1006
#define IDC_COMBO_COLOUR                1007
#define IDC_SLIDER_MIN_HUE              1008
#define IDC_EDIT_PAN_VELOCITY           1009
#define IDC_SLIDER_MAX_HUE              1010
#define IDC_BUTTON_MOVE_VELOCITY_PAN    1011
#define IDC_SLIDER_MIN_SAT              1012
#define IDC_BUTTON_GET_VELOCITY_PAN     1013
#define IDC_SLIDER_MAX_SAT              1014
#define IDC_STATIC_MIN_HUE              1015
#define IDC_STATIC_MAX_HUE              1016
#define IDC_EDIT_TILT                   1017
#define IDC_STATIC_MIN_SAT              1018
#define IDC_BUTTON_SET_TILT             1019
#define IDC_STATIC_MAX_SAT              1020
#define IDC_BUTTON_GET_TILT             1021
#define IDC_SLIDER_MIN_VAL              1022
#define IDC_STATIC_MIN_VAL              1023
#define IDC_EDIT_TILT_VELOCITY          1024
#define IDC_STATIC_MAX_VAL              1025
#define IDC_BUTTON_MOVE_VELOCITY_TILT   1026
#define IDC_SLIDER_MAX_VAL              1027
#define IDC_BUTTON_GET_VELOCITY_TILT    1028
#define IDC_BUTTON_LOAD_FILE            1029
#define IDC_BUTTON_SAVE_FILE            1030
#define IDC_STATIC_OBJECT_INFO          1031
#define IDC_STATIC_CSG                  1032
#define IDC_BUTTON_SET_PAN_TILT         1033
#define IDC_CHECK_EXPOSURE              1034
#define IDC_BUTTON_MOVE_VELOCITY_PAN_TILT 1035
#define IDC_EDIT_EXPOSURE               1036
#define IDC_SPIN_EXPOSURE               1037
#define IDC_CHECK_GAIN                  1038
#define IDC_EDIT_GAIN                   1039
#define IDC_SPIN_GAIN                   1040
#define IDC_CHECK_BRIGHTNESS            1041
#define IDC_EDIT_BRIGHTNESS             1042
#define IDC_SPIN_BRIGHTNESS             1043
#define IDC_CHECK_GAMA                  1044
#define IDC_EDIT_GAMMA                  1045
#define IDC_SPIN_GAMMA                  1046
#define IDC_BUTTON_SAVE_VIDEO_PAR       1047
#define IDC_BUTTON_CONNECTION_START_ALL 1048
#define IDC_BUTTON_GET                  1049
#define IDC_BUTTON_GET_PAN_TILT         1050
#define IDC_BUTTON_LOAD_VIDEO_PAR       1051
#define IDC_BUTTON_CONNECTION_STOP_ALL  1052
#define IDC_BUTTON_GET_PAN_TILT2        1053
#define IDC_BUTTON_GET_VELOCITY_PAN_TILT 1054
#define IDC_EDIT_SATURATION             1055
#define IDC_STATIC_CURRENT_PAN          1056
#define IDC_SPIN_SATURATION             1057
#define IDC_STATIC_CURRENT_TILT         1058
#define IDC_EDIT_ERODE                  1059
#define IDC_STATIC_CURRENT_PAN_SPEED    1060
#define IDC_EDIT_DILATE                 1061
#define IDC_STATIC_CURRENT_TILT_SPEED   1062
#define IDC_CHECK_RED                   1063
#define IDC_CHECK_BALANCE               1064
#define IDC_SPIN_ERODE                  1065
#define IDC_EDIT_RED                    1066
#define IDC_SPIN_DILATE                 1067
#define IDC_SPIN_RED                    1068
#define IDC_CHECK_BLUE                  1069
#define IDC_RADIO_OPEN                  1070
#define IDC_EDIT_BLUE                   1071
#define IDC_RADIO_CLOSE                 1072
#define IDC_SPIN_BLUE                   1073
#define IDC_STATIC_ACTIONS              1074
#define IDC_LIST_COMMS                  1075
#define IDC_EDIT_GREEN                  1076
#define IDC_BUTTON_CONNECTION_START_STOP 1077
#define IDC_SPIN_BLUE2                  1078
#define IDC_SPIN_GREEN                  1079
#define IDC_STATIC_STATUS               1080
#define IDC_EDIT_YARPPORT               1081
#define IDC_EDIT_YARPPORT_LOCAL         1082
#define IDC_EDIT_X_POS                  1083
#define IDC_EDIT_XMIN                   1084
#define IDC_EDIT_YARPPORT_REMOTE        1085
#define IDC_EDIT_Y_POS                  1086
#define IDC_CHECK_UPDATE_OBJ_INFO       1087
#define IDC_EDIT_Z_POS                  1088
#define IDC_CHECK_SHOW_IMAGE_MOVEMENT   1089
#define IDC_CHECK_ACTIONS               1090
#define IDC_CHECK_CSG                   1091
#define IDC_CHECK_FRAME_RATE            1092
#define IDC_STATIC_REMOTE               1093
#define IDC_BUTTON_STOP_PAN             1094
#define IDC_BUTTON_STOP_TILT            1095
#define IDC_BUTTON_STOP_PANTILT         1096
#define IDC_BUTTON_INIT_PAN             1097
#define IDC_BUTTON_INIT_TILT            1098
#define IDC_BUTTON_INIT_PANTILT         1099
#define IDC_BUTTON_LOOK_TO_POSITION     1100
#define IDC_RADIO_CONTROL_MODE_POSITION 1101
#define IDC_RADIO_CONTROL_MODE_VELOCITY 1102
#define IDC_STATIC_UNITS_PAN            1103
#define IDC_STATIC_UNITS_TILT           1104
#define IDC_CHECK_SHOW_IMAGE_STEREO     1105
#define IDC_XMAX                        1106
#define IDC_EDIT_YMIN                   1107
#define IDC_EDIT_YMAX                   1108
#define IDC_EDIT_ZMIN                   1109
#define IDC_EDIT_ZMAX                   1110
#define IDC_SPIN_XMIN                   1111
#define IDC_SPIN_XMAX                   1112
#define IDC_SPIN_YMIN                   1113
#define IDC_SPIN_YMAX                   1114
#define IDC_SPIN_ZMIN                   1115
#define IDC_SPIN_ZMAX                   1116
#define IDC_EDIT_MOV_HAND_IDLE          1117
#define IDC_EDIT_MOV_HAND_LOW           1118
#define IDC_EDIT_MOV_HAND_MEDIUM        1119
#define IDC_EDIT_MOV_BODY_IDLE          1120
#define IDC_EDIT_MOV_BODY_LOW           1121
#define IDC_EDIT_MOV_BODY_MEDIUM        1122
#define IDC_BUTTON_HUMANINFO_SAVE       1124
#define IDC_BUTTON_HUMANINFO_LOAD       1125
#define IDC_CHECK_HAND_MOVEMENT         1126
#define IDC_CHECK2                      1127
#define IDC_CHECK_BODY_MOVEMENT         1127
#define IDC_SLIDER_HAND_MIN_HUE         1128
#define IDC_SLIDER_HAND_MAX_HUE         1129
#define IDC_SLIDER_HAND_MIN_SAT         1130
#define IDC_SLIDER_HAND_MAX_SAT         1131
#define IDC_SLIDER_HAND_MIN_VAL         1132
#define IDC_SLIDER_HAND_MAX_VAL         1133
#define IDC_RADIO_HAND_OPEN             1134
#define IDC_RADIO_HAND_CLOSE            1135
#define IDC_SPIN_HAND_ERODE             1136
#define IDC_SPIN_HAND_DILATE            1137
#define IDC_EDIT_HAND_ERODE             1138
#define IDC_EDIT_HAND_DILATE            1139
#define IDC_STATIC_HAND_MIN_HUE         1140
#define IDC_STATIC_HAND_MAX_HUE         1141
#define IDC_STATIC_HAND_MIN_SAT         1142
#define IDC_STATIC_HAND_MAX_SAT         1143
#define IDC_STATIC_HAND_MIN_VAL         1144
#define IDC_STATIC_HAND_MAX_VAL         1145
#define IDC_CHECK1                      1146
#define IDC_CHECK_GESTURE_ACTIVE        1146
#define IDC_EDIT_POINT_SIDE_DIFF        1147
#define IDC_SPIN_POINT_SIDE_DIFF        1148
#define IDC_EDIT_HU1_PT_MIN             1149
#define IDC_EDIT_HU1_PT_MAX             1150
#define IDC_BUTTON_UPDATE_HU_POINTING   1151
#define IDC_EDIT_HU2_PT_MIN             1152
#define IDC_EDIT_HU2_PT_MAX             1153
#define IDC_EDIT_HU_POWER_M1            1154
#define IDC_EDIT_HU3_PT_MIN             1155
#define IDC_EDIT8                       1156
#define IDC_EDIT_HU3_PT_MAX             1156
#define IDC_EDIT_HU_POWER_M2            1157
#define IDC_EDIT_HU1_AG_MIN             1158
#define IDC_EDIT_HU1_AG_MAX             1159
#define IDC_EDIT_HU2_AG_MIN             1160
#define IDC_EDIT_HU2_AG_MAX             1161
#define IDC_EDIT_HU3_AG_MIN             1162
#define IDC_EDIT_HU3_AG_MAX             1163
#define IDC_BUTTON_UPDATE_HU_ABOVE      1164
#define IDC_EDIT_HU1_SG_MIN             1165
#define IDC_EDIT_HU1_SG_MAX             1166
#define IDC_EDIT_HU2_SG_MIN             1167
#define IDC_EDIT_HU2_SG_MAX             1168
#define IDC_EDIT_HU3_SG_MIN             1169
#define IDC_EDIT_HU3_SG_MAX             1170
#define IDC_BUTTON_UPDATE_HU_SIDE       1171
#define IDC_EDIT_HU_POWER_M3            1172
#define IDC_BUTTON_UPDATE_HU_POWER      1173
#define ID_MAIN_MENU_START              32771
#define ID_MAIN_MENU_STOP               32772
#define ID_MAIN_MENU_EXIT               32773
#define ID_MAIN_MENU_CONNECT_ROUTER     32774
#define ID_MAIN_MENU_PAN_TILT           32775
#define ID_MAIN_MENU_SEGMENTATION       32776
#define ID_MAIN_MENU_SEGMENTATION_FEEDBACK 32777
#define ID_MAIN_MENU_VIDEO_PARAMETERS   32778
#define ID_IMAGE_SOURCE_SVSVIDEO        32779
#define ID_IMAGE_SOURCE_SVSFILE         32780
#define ID_IMAGE_SOURCE_FILE            32781
#define ID_IMAGE_PROCESSING             32782
#define ID_IMAGE_SAVE_TO_FILE           32783
#define ID_MAIN_TASK_CONSTRUCTION       32784
#define ID_MAIN_TASK_DRINKING           32785
#define ID_MAIN_MENU_START_HAND_ACQ     32786
#define ID_MAIN_MENU_STOP_HAND_ACQ      32787
#define ID_MAIN_TASK_TUM_INTEGRATION    32788
#define ID_SOURCE_OPENCVGRABBER         32789
#define ID_IMAGE_SOURCE_OPENCVCAMERA    32790
#define ID_IMAGE_SOURCE_YARPPORT        32791
#define ID_MAIN_TASK_CONSTRUCTIONTOYROBOTFULL_SVS 32793
#define ID_MAIN_TASK_CONSTRUCTIONTOYROBOTFULL_AVT 32794
#define ID_MAIN_TASK_COLOURLEARNING     32795
#define ID_MAIN_TASK_FACETRACKING       32796
#define ID_IMAGE_FRAMESAVING            32797
#define ID_MAIN_TASK_MOBILE_ROBOT_TARGET_ACQUISITION 32798
#define ID_MAIN_TASK_TOYROBOTLEARNING   32799
#define ID_IMAGE_SOURCE_CMU1394         32800
#define ID_IMAGE_STREAM                 32801
#define ID_STREAM_ORIGINAL              32802
#define ID_STREAM_PROCESSED             32803
#define ID_MENU_IMAGE_STREAM_ORIGINAL   32804
#define ID_MENU_IMAGE_STREAM_PROCESSED  32805
#define ID_IMAGE_SHOWIMAGE              32806
#define ID_TASK_PLAYPIANO               32807
#define ID_MAIN_TASK_PLAYPIANO          32808
#define ID_SOURCE_PS3EYE                32809
#define ID_IMAGE_SOURCE_PS3EYE          32810
#define ID_TASK_HRTRANSPORT             32811
#define ID_MAIN_TASK_HRTRANSPORT        32812
#define ID_MAIN_TASK_DIFFERENTIAL_KINEMATICS 32813
#define ID_IMAGE_STEREOPROCESSING       32814
#define ID_IMAGE_SOURCE_OPENCV_VIDEO_FILE 32815
#define ID_MAIN_MENU_HUMAN_INFO         32816
#define ID_TASK_SEPARATOR_ROBOT_AROS    32817
#define ID_TASK_SEPARATOR_ROBOT_DUMBO_JUMBO 32818
#define ID_TASK_SEPARATOR_ROBOT_MEDIUMSIZED 32819
#define ID_TASK_                        32820
#define ID_TASK_TESTSTUFF               32821
#define ID_MAIN_TASK_TEST_STUFF         32822
#define ID_STEREO_DISPLAY_DISPARITY     32824
#define ID_STEREO_SAVEDISPARITYIMAGE    32825
#define ID_OPTIONS_GESTUREPARAMETERS    32826
#define ID_MAINMENU_GESTUREPARAMETERS   32827
#define ID_TASK_COMPUTERASSEMBLY        32828
#define ID_MAIN_TASK_COMPUTERASSEMBLY   32829

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32830
#define _APS_NEXT_CONTROL_VALUE         1155
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
